### ISSUE TITLE
Forward部分的实现

### ISSUE THREAD

**Issue by YAndrewL** [xqding/RealNVP#3]
Hello，我看到Forward部分的y对x是`y=x*exp(s)+t`，这和RealNVP的论文中写的是一致的，但是在一些实现中，比如[This](https://github.com/senya-ashukha/real-nvp-pytorch/blob/master/real-nvp-pytorch.ipynb)和[This](https://github.com/ikostrikov/pytorch-flows/blob/master/flows.py#L113)，y=(x-t)/exp(-s)，请问这两种应该选择哪种呢？
感谢！

**Comment by xqding** [comment]
I think they are equivalent as long as s and t are real numbers, so you can choose either one.

**Comment by YAndrewL** [comment]
Thanks a lot for the timely reply!
